export enum LocalStorageKeys {
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  CONNECTIONS = 'CONNECTIONS',
  PROJECT_ID = 'PROJECT_ID',
  USER_ID = 'USER_ID',
  PERMISSIONS = 'PERMISSIONS',
  ROLES = 'ROLES',
  INFO_PANEL_HEIGHT = 'INFO_PANEL_HEIGHT',
  MAP_STATE = 'MAP_STATE'
}
