export enum ReducerKeys {
    MAP = 'map',
    PROJECT = 'project',
    ICON = 'icon',
    DEVICE = 'device',
    DEVICE_CATEGORY = 'deviceCategory',
    TEMPLATE = 'template',
    HARDWARE = 'hardware',
    DOMAIN = 'domain',
    CONFIG_TEMPLATE = 'configTemplate',
    LOGIN_PROFILE = 'loginProfile',
    MAP_EDIT = 'mapEdit',
    MAP_STYLE = 'mapStyle',
    MAP_OPTION = 'mapOption',
    PORTGROUP = 'portgroup',
    MAP_CM = 'mapContextMenu',
    NODE = 'node',
    DOMAIN_USER = 'domainUser',
    GROUP = 'group',
    SERVER_CONNECT = 'serverConnect',
    INTERFACE = 'interface',
    USER_TASK = 'userTask',
    MAP_SELECTION = 'mapSelection',
    MAP_IMAGE = 'mapImage'
}
