export enum ApiPaths {
  ASSETS = '/assets',
  LOGIN = '/api/v1/security/login',
  REFRESH_TOKEN = '/api/v1/security/refresh',
  LOGOUT = '/api/v1/logout',
  GET_MAP_DATA = '/api/v1/map/get_data',
  GET_PROJECTS = '/api/v1/project/',
  GET_GEN_NODE_DATA = '/api/v1/node/gen_data',
  GET_ICONS = '/api/v1/icon/',
  GET_DEVICES = '/api/v1/device/',
  GET_TEMPLATES = '/api/v1/template/',
  GET_HARDWARES = '/api/v1/hardware/',
  GET_DOMAINS = '/api/v1/domain/',
  GET_CONFIG_TEMPLATES = '/api/v1/configtemplate/',
  GET_LOGIN_PROFILES = '/api/v1/loginprofile/',
}
