export enum RouteSegments {
  ROOT = '/',
  LOGIN = 'login',
  DASHBOARD = 'dashboard',
  PROJECTS = 'projects',
  DEVICES = 'devices',
  TEMPLATES = 'templates',
  REMOTE = 'remote',
  SETTINGS = 'settings',
  HELP = 'help',
  MAP = 'map',
  USER_PROFILE = 'user-profile',
  ADD_PROJECT = 'projects/add',
  EDIT_PROJECT = 'projects/edit',
  EXPORT_IMPORT = 'projects/export-import',
  DEVICES_TEMPLATE = 'devices/device_template',
  HARDWARE = 'devices/hardware',
  CONFIG_TEMPLATES = 'templates/config',
  NETWORK_TEMPLATES = 'templates/network',
  CONNECT_REMOTE = 'remote/connect',
  CONNECTION_PROFILES = 'remote/connection-profiles',
  APP_PREFERENCES = 'settings/app-preferences',
  MAP_PREFERENCES = 'settings/map-preferences',
  USER_GUIDE = 'help/user-guide',
  ABOUT = 'help/about',
}
